shinyProtocol <- function(){
  conn <- dbConnect(MySQL(), user = 'g1090425', password = 'group4332', dbname = 'g1090425', host = 'mydb.ics.purdue.edu')
  NewEngland <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'CT' OR State = 'ME' OR State = 'MA' OR State = 'NH' OR State = 'RI' OR State = 'VT' ;"))
  NewEnglandC <- length(NewEngland$State)
  MidAtlantic <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'NJ' OR State = 'NY' OR State = 'PA' ;"))
  MidAtlanticC <- length(MidAtlantic$State)
  ENC <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'IL' OR State = 'IN' OR State = 'MI' OR State = 'OH' OR State = 'WI' ;"))
  ENCC <- length(ENC$State)
  WNC <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'IA' OR State = 'KS' OR State = 'MN' OR State = 'MO' OR State = 'NE'OR State = 'ND' OR State = 'SD';"))
  WNCC <- length(WNC$State)
  SA <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'DE' OR State = 'FL' OR State = 'GA' OR State = 'MD' OR State = 'NC'OR State = 'SC' OR State = 'VA' OR State = 'DC' OR State = 'WV';"))
  SAC <- length(SA$State)
  ESC <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'AL' OR State = 'KY' OR State = 'MS' OR State = 'TN';"))
  ESCC <- length(ESC$State)
  WSC <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'AR' OR State = 'LA' OR State = 'OK' OR State = 'TX';"))
  WSCC <- length(WSC$State)
  Mount <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'AZ' OR State = 'CO' OR State = 'ID' OR State = 'MT' OR State = 'NV'OR State = 'NM' OR State = 'UT' OR State = 'WY';"))
  MountC <- length(Mount$State)
  Pac <- fetch(dbSendQuery(conn, "SELECT State FROM Warehouse WHERE State = 'AK' OR State = 'CA' OR State = 'HI' OR State = 'OR' OR State = 'WA';"))
  PacC <- length(Pac$State)
  passBack <- c(NewEnglandC,MidAtlanticC,ENCC,WNCC,SAC,ESCC,WSCC,MountC,PacC)
  return(passBack)
}